### test user creation
POST http://localhost:3000/users/register
Content-Type: application/json

{   
    "email": "fran.b@gmail.com",
    "user_name": "caca",
    "password":"abcde123"
}

### test login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "fran.b@gmail.com",
    "password":"abcde123"
}

### drop table
DELETE http://localhost:3000/users

### get users
GET http://localhost:3000/users