### test user creation
POST http://localhost:3030/register
Content-Type: application/json

{
    "email": "fran.b@gmail.com",
    "password":"abcde123"
}

### test login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "fran.b@gmail.com",
    "password":"abcde123"
}

### drop table
delete http://localhost:3030/users