import { z } from 'zod'

const UserRole = z.enum(['ADMIN', 'USER', 'GUEST'])

export const userSchema = z.object({
  // We expect a UUID generated by the database (e.g., by Prisma or the DB itself).
//   id: z.uuid({ message: "Invalid UUID" }),

  //   username: z.string()
  //     .min(3, { message: "Username must be at least 3 characters long." })
  //     .max(50, { message: "Username cannot be longer than 50 characters." })
  //     .regex(/^[a-zA-Z0-9_]+$/, { message: "Username can only contain letters, numbers, and underscores." }),

  email: z.email({ message: 'Invalid email address.' }),

  user_name: z.string().min(0).max(20),

  // 🔐 IMPORTANT: This is for validation, NOT for storage.
  // You should always HASH the password before saving it to a database.
  password: z.string()
    .min(8, { message: 'Password must be at least 8 characters long.' })
    .regex(/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/, {
      message: 'Password must contain at least one letter and one number.'
    }),

  //   role: UserRole.default('USER'), // Default role to 'USER' if not provided

  createdAt: z.date().default(() => new Date()),
  updatedAt: z.date().default(() => new Date())
})

export function validateRegister (data) {
  const result = userSchema.safeParse(data)
  return result
}
